module.exports = {
  docs: [
    'intro',
    {
      type: 'category',
      label: '00. Introduction',
      items: [
        {
          type: 'autogenerated',
          dirName: '00-introduction',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 01: Foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01-foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 02: Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 03: AI Robot Brain (NVIDIA Isaac™)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-03-ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 04: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-04-vision-language-action',
        },
      ],
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendix',
        },
      ],
    },
  ],
};
